name: telegram-commit
 
on:
  push:
    branches:
      - main
      - "dev/v10"
 
jobs:
  send_msg:
    name: Send message to Telegram Chat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Sending...
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_GROUP }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ğŸ“Œ ${{ github.event.commits[0].message }} #a2iga
 
            ğŸ‘¨â€ğŸ’» by @${{ github.actor }} / ğŸ”— https://github.com/${{ github.repository }}/commit/${{github.sha}}
