 
 â€‹nameâ€‹:Â â€‹telegram-commit 
  
 â€‹onâ€‹: 
 â€‹Â Â â€‹pushâ€‹: 
 â€‹Â Â Â Â â€‹branchesâ€‹: 
 â€‹Â Â Â Â Â Â -Â â€‹main 
 â€‹Â Â Â Â Â Â -Â "â€‹dev/v10"
  
 â€‹jobsâ€‹: 
 â€‹Â Â â€‹send_msgâ€‹: 
 â€‹Â Â Â Â â€‹nameâ€‹:Â â€‹SendÂ messageÂ toÂ TelegramÂ Chat 
 â€‹Â Â Â Â â€‹runs-onâ€‹:Â â€‹ubuntu-latest 
 â€‹Â Â Â Â â€‹stepsâ€‹: 
 â€‹Â Â Â Â Â Â -Â â€‹nameâ€‹:Â â€‹Sending... 
 â€‹Â Â Â Â Â Â Â Â â€‹usesâ€‹:Â â€‹appleboy/telegram-action@master 
 â€‹Â Â Â Â Â Â Â Â â€‹withâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â â€‹toâ€‹:Â â€‹${{Â secrets.TG_GROUPÂ }} 
 â€‹Â Â Â Â Â Â Â Â Â Â â€‹tokenâ€‹:Â â€‹${{Â secrets.TG_BOT_TOKENÂ }} 
 â€‹Â Â Â Â Â Â Â Â Â Â â€‹messageâ€‹:Â â€‹| 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â ğŸ“ŒÂ ${{Â github.event.commits[0].messageÂ }}Â #a2iga
  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â ğŸ‘¨â€ğŸ’»Â byÂ @${{Â github.actorÂ }}Â /Â ğŸ”—Â https://github.com/${{Â github.repositoryÂ }}/commit/${{github.sha}}
